### ISSUE TITLE
strange abstraction with globals class

### ISSUE THREAD

**Issue by danmarsden** [grabs/moodle-auth_companion#1]
Stuff like  $DB = gl::db(); is not really the correct moodle syntax - 

you should just use 
global $DB; 
at the top of your functions - there is really no reason to abstract globals like this.

I'd delete your whole "globals.php" file and rewrite it to look more like existing moodle code.

It's not a blocker for approval but would definitely fail a Moodle core review.

**Comment by grabs** [comment]
Hi Dan,
thank you for pointing this out. It was a good way for autocompletion in vscode. I removed it now as you suggested and found another way around.
Best Andreas
