### ISSUE TITLE
user_login() function looks incorrect

### ISSUE THREAD

**Issue by danmarsden** [grabs/moodle-auth_companion#3]
if you take a look at the "nologin" auth method you will see it just returns "false" - your plugin appears to return true in some cases which doesn't seem correct to me.

I think this is a blocker for approval.

**Comment by danmarsden** [comment]
https://github.com/grabs/moodle-auth_companion/blob/main/auth.php#L75

**Comment by grabs** [comment]
Hi Dan,
I fixed this. Now it will always be "false" returned.
Thanks Andreas
