### ISSUE TITLE
companion login should probably clear $_SESSION vars?

### ISSUE THREAD

**Issue by danmarsden** [grabs/moodle-auth_companion#4]
I suspect the switch between users should be clearing the $_SESSION and $GLOBALS['SESSION'] vars - take a look at the
\core\session\manager::loginas() function to see how it switches users - clearing those vars before switching the user - especially as your code doesn't trigger a logout() process.

**Comment by danmarsden** [comment]
I think this is probably a blocker for approval - I think you need to make sure the Session vars are cleared during the switch of users - both from user to companion and then back again.

**Comment by grabs** [comment]
Hi Dan,
thank you for this important tip.
Now I call `\core\session\manager::init_empty_session(true);` while switching to the companion and back.
Best Andreas
