### ISSUE TITLE
Companion authentication icon always visible in the top navbar even when the plugin is disable

### ISSUE THREAD

**Issue by xtof3d** [grabs/moodle-auth_companion#5]
Thanks for developing this plugin.
We encounter a problem when the plugin is installed but disabled.
The companion account icon is always visible in the navigation bar.
To test this issue : 
- As an administrator, go to the authentication plugin management page and disable the plugin by crossing out the eye icon :
![image](https://github.com/grabs/moodle-auth_companion/assets/166130843/381bea17-9bca-4917-9943-0dee993d547e)
- With a teacher account, go to a course and notice that the companion icon is still visible while the link to switch to companion has disappeared from the personal menu :
![image](https://github.com/grabs/moodle-auth_companion/assets/166130843/67ab691b-91e3-45f0-add4-72b10e416740)
- If you click on the companion icon a message indicates that you are using your companion account but this does not work :
![image](https://github.com/grabs/moodle-auth_companion/assets/166130843/25973fea-e269-411b-ba09-33d43a7a58bc)
Thank you for your attention.

**Comment by grabs** [comment]
Thank you for reporting this. In the last version this problem has been fixed.
