### ISSUE TITLE
Undefined property: stdClass::$auth

### ISSUE THREAD

**Issue by JokaJukka** [grabs/moodle-auth_companion#6]
Hey there!
On our production instance there is an influx of the following warning message:
```
Warning: Undefined property: stdClass::$auth; file /var/www/moodle/auth/companion/classes/util.php; line 130
```

We are using Moodle 4.4.4 and auth_companion v4.5.0.

Thanks for your help!

**Comment by grabs** [comment]
Hi, thank you for reporting this. Unfortunately I can't reproduce this message at all :(.
Can you give me some guidance how to get this message?

**Comment by JokaJukka** [comment]
Hey there,
some additional info: PHP Version 8.3.13, using official Docker fpm container
I can reproduce it just fine on our local env on all the pages without being logged in... When logged in, the warning seems to disappear.

**Comment by grabs** [comment]
Hi, thanks for the quick reply. The part "without being logged in" was the important part :).
I fixed it in the last version.
